import type { NextPage } from 'next';
import Head from 'next/head';
import Link from 'next/link';

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <span>Ссылка на админку:</span>
        <Link href="/admin">
          <span style={{ color: 'red', marginLeft: 10, cursor: 'pointer' }}>ссылка</span>
        </Link>
      </div>
    </div>
  );
};

export default Home;
